name: Github Action Test

on:
  workflow_dispatch:
    inputs:
      deploy_type:
        type: choice
        required: true
        description: "정기배포 여부를 선택해주세요."
        options:
          - myrealtrip
          - hotfix
      deploy_tag:
        description: "태그명을 직접 작성할 경우 입력해주세요."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Create Release
      id: create_release
      uses: actions/github-script@v5
      env:
        TAG_NAME: ${{ github.event.inputs.deploy_tag || github.event.inputs.deploy_type }}
      with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: ${{ env.TAG_NAME }},
              sha: context.sha
            })
