name: Github Action Test (${{ github.event.inputs.input_deploy }})

on:
  workflow_dispatch:
    inputs:
      input_deploy:
        type: choice
        required: true
        description: "정기배포 여부를 선택해주세요."
        options:
          - myrealtrip
          - hotfix
#       input_hotfix_count:
#         description: "핫픽스인 경우 횟수를 입력해주세요."
#         default: "1"
      input_tag:
        description: "태그명을 직접 작성할 경우 입력해주세요."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Get current date
      id: date
      run: echo "::set-output name=datetime::$(TZ=UTC-9 date +'%Y-%m-%d %H:%M:%S')"
      
    - name: Set Tag Name
      id: tag
      env:
        BASE_TAG: ${{ github.event.inputs.input_deploy }}-$(TZ=UTC-9 date +'%Y%m%d')
        HOTFIX_TAG: ${{ env.BASE_TAG }}-$(TZ=UTC-9 date +'%H%M')
      run: |
        if [ ${{github.event.inputs.input_tag }} ]; then
          # 태그명 직접 작성
          echo "::set-output name=name::${{ github.event.inputs.input_tag }}"
        else
          # 태그명 미작성 - myrealtrip(정기) or hotfix(핫픽스)
          echo "::set-output name=name::${{ github.event.inputs.input_deploy == 'myrealtrip' && env.BASE_TAG || env.HOTFIX_TAG }}"
        fi
    
    - name: Create Release
      uses: actions/github-script@v5
      with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.tag.outputs.name }}",
              sha: context.sha
            })
