name: Github Action Test

on:
  workflow_dispatch:
    inputs:
      input_deploy:
        type: choice
        required: true
        description: "정기배포 여부를 선택해주세요."
        options:
          - myrealtrip
          - hotfix
      input_tag:
        description: "태그명을 직접 작성할 경우 입력해주세요."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(TZ=UTC-9 date +'%Y%m%d')"
    
    - name: Set Tag Name
      id: tag
      run: |
        if [ ${{ github.event.inputs.input_tag }} ]; then
          # 태그명 직접 작성
          echo "::set-output name=name::${{ github.event.inputs.input_tag }}"
        elif [ ${{ github.event.inputs.input_deploy == 'hotfix' }} ]; then
          # 태그명 미작성 - hotfix
          echo "::set-output name=name::${{ github.event.inputs.input_deploy }}-${{ steps.date.outputs.date }}-1"
        else
          # 태그명 미작성 - myrealtrip(정기)
          echo "::set-output name=name::${{ github.event.inputs.input_deploy }}-${{ steps.date.outputs.date }}"
        fi
      shell: bash
    
    - name: Create Release
      uses: actions/github-script@v5
      with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.tag.outputs.name }}",
              sha: context.sha
            })
