name: Github Action Test

on:
  workflow_dispatch:
    inputs:
      deploy_type:
        type: choice
        required: true
        description: "정기배포 여부를 선택해주세요."
        options:
          - myrealtrip
          - hotfix
      deploy_tag:
        description: "태그명을 직접 작성할 경우 입력해주세요."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(TZ=UTC-9 date +'%Y%m%d')"
    
    - name: Create Release
      id: create_release
      uses: actions/github-script@v5
      env:
        TAG_NAME: ${{ steps.date.outputs.date }}
      with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.TAG_NAME }}",
              sha: context.sha
            })
