name: Build Production

on:
  workflow_dispatch:
    inputs:
      deploy_type:
        type: choice
        required: true
        description: "배포타입: myrealtrip(정기)/hotfix(핫픽스)"
        options:
          - myrealtrip
          - hotfix

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    # Set tag name by auto or input
    - name: Set Release Tag
      id: tag
      env:
        MRT_TAG: ${{ github.event.inputs.deploy_type }}-$(TZ=UTC-9 date +'%Y%m%d%H%M')
      run: echo "::set-output name=name::${{ env.MRT_TAG }}

    # Create tag on present commit
    - name: Create Tag
      uses: actions/github-script@v5
      env:
        TAG_NAME: ${{ github.event.inputs.deploy_type }}-$(TZ=UTC-9 date +'%Y%m%d%H%M')
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ steps.tag.outputs.name }}",
            sha: context.sha
          })
