name: Build Production

on:
  workflow_dispatch:
    inputs:
      # SelectBox : Deploy type for tags
      deploy_type:
        type: choice
        required: true
        description: "배포타입: myrealtrip(정기), hotfix(핫픽스)"
        options:
          - myrealtrip
          - hotfix
      # CheckBox : Is allowed to change version after deploy
      version_change:
        type: boolean
        description: "버전변경 포함(서버배포 확인 필수)"
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

#     - name: Set Slack Message
#       id: success-slack-message
#       uses: haya14busa/action-cond@v1
#       with:
#         cond: ${{ github.event.inputs.version_change == 'true' }}
#         if_true: <!here> 🌟프론트엔드 `${{ env.deploy_target }}` 배포가 완료 되었습니다.🥳\n\n- sha -> ${{ '7d8cc70c15c2b1d85525f0e8408001adf22f526e' }}\n✅버전이 변경되었으니 확인해주세요.
#         if_false: <!here> 🌟프론트엔드 `${{ env.deploy_target }}` 배포가 완료 되었습니다.🥳\n\n- sha -> ${{ '7d8cc70c15c2b1d85525f0e8408001adf22f526e' }}\n⚠Frontend 버전 변경을 진행해주세요.
      
    - name: Set Slack Message
      id: success-slack-message
      run: |
          if ${{ github.event.inputs.version_change == 'true' }} then;
            echo "::set-output name=message::<!here> 🌟프론트엔드 `${{ env.deploy_target }}` 배포가 완료 되었습니다.🥳\n\n- sha -> ${{ '7d8cc70c15c2b1d85525f0e8408001adf22f526e' }}\n✅버전이 변경되었으니 확인해주세요."
          else
            echo "::set-output name=message::<!here> 🌟프론트엔드 `${{ env.deploy_target }}` 배포가 완료 되었습니다.🥳\n\n- sha -> ${{ '7d8cc70c15c2b1d85525f0e8408001adf22f526e' }}\n⚠Frontend 버전 변경을 진행해주세요."
          fi

    - name: Use Slack Message
      run: echo "${{ steps.success-slack-message.outputs.value }}"


