name: Build Production

on:
  workflow_dispatch:
    inputs:
      deploy_type:
        type: choice
        required: true
        description: "배포타입: myrealtrip(정기)/hotfix(핫픽스)"
        options:
          - myrealtrip
          - hotfix

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Set tag name by auto or input
    - name: Get tag datetime
      id: tag_datetime
      run: echo "::set-output name=name::$(TZ=UTC-9 date +'%ym%d_%H%M')"

    # Create tag on present commit
    - name: Create Tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ github.event.inputs.deploy_type }}-${{ steps.tag_datetime.outputs.name }}",
            sha: context.sha
          })
